version: "3.9"
services:
  eflow:
    container_name: eflow_db
    build:
      context: .
      dockerfile: Dockerfile
    hostname:
        mssql-samplesdb
    domainname:
        eprac.com    
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "14333:1433"        
    cpu_count: 4
    mem_limit: 4Gb
